

def show_gloss_term(key, term_dict):
    if key in term_dict.keys():
        return term_dict[key]
    else:
        return('Something went wrong. Select a term in the list and try again.')


glossary_list = ["Artwork_ID", "Artwork_ID_Level2", "Artist", "Other_Artist_Attribution", "Artwork_Date",
                 "Artwork_Title", "Artwork_State_of_Conservation", "Art_Form",
                 "Artwork_Description", "Artwork_Type", "Artwork_Shape", "Artwork_Material",
                 "Artwork_Technique_Info", "Artwork_Height_x_Width", "Artwork_Dimension_Type",
                 "Artwork_Iconography", "Cultural_Institution", "Artwork_LocBuilding", "Relation_Type_with_Other_Artwork",
                 "Literature_Ref_Short_Title", "Artwork_Style_GeographicalOrigin",
                 "Literature_Reference", "ArchitectureObj_Name", "ArchitectureObj_Carrier", "ArchitectureObj_City",
                 "Text_in_Artwork", "Photo_Archival_Date", "Photo_Photothek_Section", "Photo_Administrator",
                 "Photo_Negative_Number", "Photo_Old_Negative_Number", "Photo_Material", "Photo_Notes", "Photo_Type",
                 "Photo_Color", "Photographer", "Photo_Date", "Photo_Acquisition_Process", "Photo_Provenance",
                 "Digital_Photo_Storage_Date", "Digital_Photo_File_Format", "Photo_Equipment", "Photo_Dimensions",
                 "Photo_Subject", "Photo_Credits", "Photo_Old_Archive_Section",
                 "Photo_Preservation_State"]

glossary_dict = {"Artwork_ID": '''<p><b>Artwork_ID</b>: A unique <b>identifier for an artwork</b> consisting entirely of numbers.
                It is automatically generated by the KHI when an artwork is cataloged in the database.
                Artworks can consist of multiple components, each of which is identified through a specific ID. In this notebook,
                they are designated as <code>Artwork_ID_Level2</code> and <code>Artwork_ID_Level3</code>,
                depending on their hierarchical level within the database record. Artworks with hierarchical strcutre,
                such as a mural painting within a series, or a chapel within a church, 
                typically show IDs with levels 2 or above.</p>
                <p><i>Examples:</i></p>
                <ul><li>07703279</li></ul>''',
                 "Artwork_ID_Level2": '''<p><b>Artwork_ID</b>: A unique <b>identifier for an artwork</b> consisting entirely of numbers.
                It is automatically generated by the KHI when an artwork is cataloged in the database.
                Artworks can consist of multiple components, each of which is identified through a specific ID. In this notebook,
                they are designated as <code>Artwork_ID_Level2</code> and <code>Artwork_ID_Level3</code>,
                depending on their hierarchical level within the database record. Artworks with hierarchical strcutre,
                such as a mural painting within a series, or a chapel within a church, 
                typically show IDs with levels 2 or above.</p>
                <p><i>Examples:</i></p>
                <ul><li>07503261,T,001, where "T" stands for "Teil" ("Part")</li></ul>''',
                "Artist": '''<p><b>Artist</b>: Name of the creator or manufacturer associated with an artwork, usually presented
                 in the format "Last Name, First Name". Artworks may be associated with one or multiple artists.</p>
                <p><i>Examples:</i></p>
                <ul><li>Botticelli, Sandro</li></ul>''',
                "Other_Artist_Attribution": '''<p><b>Other_Artist_Attribution</b>: Name of a creator or manufacturer 
                previously credited with the creation or production of an artwork. However, this attribution has either
                not been verified subsequently or has been discredited due to a lack of authentication or proven inaccuracy.</p>
                <p><i>Examples:</i></p>
                <ul><li>alternative Zuschreibung: Perugino (alternative attribution: Perugino)</li></ul>''',
                "Artwork_Date": '''<p><b>Artwork_Date</b>: It provides information regarding the dates associated with an artwork. It includes
                details on the type of date (such as creation, restoration, or modifications), along with the
                corresponding year range or specific year.
                <p><i>Examples:</i></p>
                <ul>
                <li>Datierung: 1401/1600 (the period during which the artwork was created falls within the range of the years specified)</li>
                <li>Datierung: 1453-1454 (The specific start and end dates representing the production period of the artwork)</li>
                </ul>''',
                "Artwork_Title": '''<p><b>Artwork_Title</b>: The title associated with an artwork, usually in German. It
                serves as a descriptor or identifier for the artwork, and it may provide information about the type of artwork or its content.</p>
                <p><i>Examples:</i></p>
                <ul><li>Kreuzigung Christi (Crucifixion of Christ)</li></ul>
                <ul><li>Altchristlicher Sarkophag (Early Christian Sarcophagus)</li></ul>
                ''',
                "Artwork_State_of_Conservation": '''<p><b>Artwork_State_of_Conservation</b>: It provides information about the condition
                of an artwork, detailing any damages incurred, objects that may have been destroyed, or items that are 
                currently unfindable.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>unvollendet (unfinished)</li>
                <li>beschädigt (damaged)</li>
                <li>Fragment (fragment)</li>
                <li>verschollen (missing)</li>
                </ul>''',
                "Art_Form": '''<p><b>Art_Form</b>: It describes a specific category of creative activity,
                such as painting, sculpture, architecture, or drawing, each with its own techniques and mediums.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Malerei (Painting)</li>
                <li>Wandmalerei (Mural Painting)</li>
                <li>Skulptur (Sculpture)</li>
                <li>Architektur (Architecture)</li>
                <li>Zeichenkunst (Drawing)</li>
                </ul>''',
                "Artwork_Description": '''<p><b>Artwork_Description</b>: It provides additional descriptive details about the shape of an artwork.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Reliefplastik (relief sculpture)</li>
                <li>Rundplastik (statuary)</li>
                </ul>''',
                "Artwork_Type": '''<p><b>Artwork_Type</b>: It provides information about the type of object.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Bild (painting)</li>
                <li>Wandbild (mural painting)</li>
                <li>Kruzifix (crucifix)</li>
                <li>Kirche (church)</li>
                <li>Portaldekoration (Portal Decoration)</li>
                <li>Spiegel (mirror)</li>
                </ul>''',
                "Artwork_Shape": '''<p><b>Artwork_Shape</b>: It provides additional information on the shape of an object.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Lünette (lunette)</li>
                <li>rund (round)</li>
                <li>Polyptychon (polyptych)</li>
                </ul>''',
                "Artwork_Material": '''<p><b>Artwork_Material</b>: It refers to the substances or resources used by 
                artists to create a work of art.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Öl (oil)</li>
                <li>Leinwand (canvas)</li>
                <li>Putz (plaster)</li>
                <li>Marmor (marble)</li>
                </ul>''',
                "Artwork_Technique_Info": '''<p><b>Artwork_Technique_Info</b>: It provides additional details on 
                the technique or materials used by an artist to create an object.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Freskomalerei (fresco painting)</li>
                <li>vergoldet (gold-plated)</li>
                <li>Majolika (majolica)</li>
                </ul>''',
                "Artwork_Height_x_Width": '''<p><b>Artwork_Height_x_Width</b>: Artwork dimensions expressed as "height x width" in cm, 
                typically for paintings or drawings.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>49 x 38 cm</li>
                <li>117,5 x 137 cm</li>
                </ul>''',
                "Artwork_Dimension_Type": '''<p><b>Artwork_Dimension_Type</b>: It specifies a particular 
                artwork dimension (height, width, depth, diameter) with the corresponding value in cm, usually for 
                sculptures or architecture.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Durchmesser: 25 cm (diameter)</li>
                <li>Tiefe: 89 cm (depth)</li>
                </ul>''',
                "Artwork_Iconography": '''<p><b>Artwork_Iconography</b>: It describes the themes, symbols, 
                and subjects depicted in the artwork, using <a href="https://iconclass.org" target="_blank">Iconclass codes</a> for standardized classification.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>11H(Francis) (code for Saint Francis of Assisi)</li>
                <li>94G234 (Achilles kills Hector)</li>
                <li>11F43 (Madonna: Mary sitting on the ground, the Christ-child in her lap)</li>
                <li>25GG (fantastic plants, fabulous vegetation)</li>
                </ul>''',
                "Cultural_Institution": '''<p><b>Cultural_Institution</b>: Information about 
                the cultural institution associated with an artwork and its relationship with the object.
                When filtering data by cultural institution, you can also input an inventory number or its city
                 for more accurate searches.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Verwalter: Galleria degli Uffizi, Florenz (Administrator: Galleria degli Uffizi, Florence)</li>
                <li>Vorbesitzer: Galleria dell'Accademia, Florenz (Previous owner: Galleria dell'Accademia, Florence)</li>
                <li>früherer Verwalter: Kaiser-Friedrich-Museum, Berlin (former administrator: Kaiser-Friedrich-Museum, Berlin)</li>
                </ul>''',
                "Artwork_LocBuilding": '''<p><b>Artwork_LocBuilding</b>: It refers to a building associated with an artwork, especially
                for immovable objects. It provides information about the relationship between the artwork and the building, 
                and details about the building location.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Standort: Santa Maria Assunta, Spoleto (Location: Santa Maria Assunta, Spoleto)</li>
                <li>Fundort: Augusteum, Herculaneum (place of discovery: Augusteum, Herculaneum)</li>
                <li>Herkunftsort: Scuola di Sant'Orsola, Venedig (Place of origin: Scuola di Sant'Orsola, Venice)</li>
                </ul>''',
                "Relation_Type_with_Other_Artwork": '''<p><b>Relation_Type_with_Other_Artwork</b>: Describes the relationship 
                between an artwork and another object within the database, identified by its Artwork ID. It explains various types of 
                connections, such as linking an artwork component to its main object.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Zusammenhang: 07650001 (Connection: 07650001)</li>
                <li>Teil von: 70013973 (Part of: 70013973)</li>
                </ul>''',
                "Literature_Ref_Short_Title": '''<p><b>Literature_Ref_Short_Title</b>: Refers to relevant literature 
                about the artwork or the related photographs, expressed with standard short titles for simplicity.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Berenson, Lorenzo Lotto, 1956</li>
                <li>Fotokatalog Alinari, Venezia (u.a.), 1906</li>
                </ul>''',
                "Artwork_Style_GeographicalOrigin": '''<p><b>Artwork_Style_GeographicalOrigin</b>: Provides information 
                about the specific style or geographical origin of an artwork, useful when 
                details about the artist are not available.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>römisch (Roman style)</li>
                <li>byzantinisch (Byzantine style)</li>
                <li>sizilianisch (Sicilian style)</li>
                </ul>''',
                "Literature_Reference": '''<p><b>Literature_Reference</b>: Includes extensive information about literature resources 
                that do not have a shorter citation form (<code>Literature_Ref_Short_Title</code>). 
                It occasionally includes web resources.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Zampetti, P., La pittura marchigiana dell '400, Venedig, 1969, Abb. 91</li>
                <li>Gould, Cecil, The Paintings of Correggio, London 1976, S. 60-62</li>
                <li><a href="https://catalogo.uffizi.it/it/29/ricerca/detailiccd/1185232/" target="_blank">https://catalogo.uffizi.it/it/29/ricerca/detailiccd/1185232/ (2023.04.04)</a></li>
                </ul>''',
                "ArchitectureObj_Name": '''<p><b>ArchitectureObj_Name</b>: It provides the name of an artwork or its 
                components if the database record refers to an architectural object. 
                </p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Santa Maria del Fiore</li>
                <li>Palazzo Farnese</li>
                <li>Nordostfassade (North-east facade)</li>
                </ul>''',
                "ArchitectureObj_Carrier": '''<p><b>ArchitectureObj_Carrier</b>: Name of a specific 
                religious orders related with an architectural object.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Augustiner (Order of Saint Augustine)</li>
                <li>Dominikaner (Dominican Order)</li>
                </ul>''',
                "ArchitectureObj_City": '''<p><b>ArchitectureObj_City</b>: It refers to the city where an architectural 
                object is located.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Verona</li>
                <li>Florenz</li>
                <li>Padua</li>
                </ul>''',
                "Text_in_Artwork": '''<p><b>Text_in_Artwork</b>: It includes any text depicted in an artwork, 
                detailing the type of text and its position.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Signatur (Maler): Lucas Signorellus Pingebat MDVII</li>
                <li>Inschrift: IERONIMUS IOHANNIS DE CAMERINO DEPINSIT</li>
                </ul>''',
                "Photo_Archival_Date": '''<p><b>Photo_Archival_Date</b>: The date of archival of a photograph. 
                For recent photographs, it is the date of cataloguing. 
                Archival dates of photographs archived before 1993 can be searched on the following website: 
                <a href="http://zdr.khi.fi.it/" target="_blank">http://zdr.khi.fi.it/</a></p>
                <p><i>Examples:</i></p>
                <ul>
                <li>1911-03-01 (originally in the format 1911.03, converted for filtering)</li>
                <li>2001-04-04 (originally in the format 2001.04.04, converted for filtering)</li>
                </ul>''',
                "Photo_Photothek_Section": '''<p><b>Photo_Photothek_Section</b>: It refers to the Photothek Section in 
                which a photograph is located. Section categories are <b>Architecture, Sculpture, Painting and Applied Arts</b>. 
                Photographs of <b>Antique art</b> (architecture, sculpture, painting and mosaic) form their own section.</br>
                The <b>Architecture</b> section is divided into epochs and, within these, into regions and locations.</br>
                The <b>Painting and Sculpture</b> sections are likewise organized into epochs. Within each epoch, the works
                 of known artists are arranged in alphabetical order of artist name, followed by anonymous works 
                 arranged according to their current location. Drawings, prints and miniatures are integrated into 
                 these sections on the basis of what they show. The Painting section also includes the sub-division
                  Portraits and Self-portraits in the Uffizi.</br>
                  The <b>Applied Arts</b> section is organized by material and object type, and within each respective 
                category by epoch. (Source: 
                <a href="https://www.khi.fi.it/en/photothek/bestand.php" target="_blank">Photothek: Holdings</a>)</p>
                <p></p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Mal. Ren. (Painting Renaissance)</li>
                <li>Mal. Bar. (Painting Baroque)</li>
                <li>Arch. Rom. u. Got (Romanesque and Gothic Architecture)</li>
                <li>Arch. Ren. u. Bar. (Renaissance and Baroque Architecture)</li>
                <li>Sc. Antik (Antique Sculpture)</li>
                <li>Sc. Ren (Renaissance Sculpture)</li>
                <li>Kunstg. Edelmet. (Applied Arts, Precious Metals</li>
                <li>Kunstg. Textil (Applied Arts, Textile)</li>
                <li>Z. Sc. Ren. (Drawing of Renaissance Sculpture)</li>
                </ul>''',
                "Photo_Administrator": '''<p><b>Photo_Administrator</b>: Details about the name of the 
                administrator and owner of a photograph, if available. Digital images of historical photographs present both the 
                original photographer's name and "KHI".</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Alinari</li>
                <li>KHI-Alinari</li>
                <li>Special Collections, Fine Arts Library, Harvard University</li>
                <li>ICCD</li>
                </ul>''',
                "Photo_Negative_Number": '''<p><b>Photo_Negative_Number</b>: The negative number assigned to a 
                photograph, sometimes including photographer information.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Anderson 40433</li>
                <li>821/17</li>
                <li>1091.72 Sigismondi</li>
                </ul>''',
                "Photo_Old_Negative_Number": '''<p><b>Photo_Old_Negative_Number</b>: It provides the old negative number 
                of a photograph, if available, along with the name of the corresponding archive.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>4722/23 Artini</li>
                <li>Brogi 1807?</li>
                </ul>''',
                "Photo_Material": '''<p><b>Photo_Material</b>: Describes the material and/or process of production
                of a photograph.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Albuminpapier (Albumen Print)</li>
                <li>Glasplatte (Glass plate)</li>
                <li>Silbergelatineabzug (Gelatine silver process)</li>
                <li>Kohledruck (Carbon print)</li>
                <li>Kollodiumabzug (Collodion process)</li>
                <li>Cyanotypie (Cyanotype)</li>
                </ul>''',
                "Photo_Notes": '''<p><b>Photo_Notes</b>: Additional relevant information about a photograph.
                For example, it is used to include information about historical photographs ("Cimelia"),
                or to report if a photograph is missing.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Cimelia Photographica (Standardformat)</li>
                <li>Foto fehlt, 2015.07.15</li>
                </ul>''',
                "Photo_Type": '''<p><b>Photo_Type</b>: Information about the type of photograph,
                if it is a reproduction.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Klischee (cliché)</li>
                <li>Postkarte (postcard)</li>
                <li>Druck (print)</li>
                </ul>''',
                "Photo_Color": '''<p><b>Photo_Color</b>: Details about the color of a photograph. 
                It can only assume the values <i>color</i> and <i>monochrom</i></p>''',
                "Photographer": '''<p><b>Photographer</b>: The name of the photographer, if available, 
                typically expressed in the format "Last Name, First Name". If the photographer is unknown, 
                the field contains the value <i>unbekannt</i> (unknown). Digital image records of historical photographs
                present both the name of the original photographer and of the digital laboratory of the KHI.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Anderson, Domenico</li>
                <li>Alinari</li>
                <li>Digitallabor KHI nach historischer Vorlage</li>
                <li>Sigismondi, Roberto</li>
                <li>unbekannt (unknown)</li>
                </ul>''',
                "Photo_Date": '''<p><b>Photo_Date</b>: Date of creation of a photograph. For historical photographs, 
                if the creation date is unavailable, an estimate based on technical and contextual 
                information is provided.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>vor 1896 (before 1896)</li>
                <li>um 1966 (around 1966)</li>
                <li>nach 1885 (after 1885)</li>
                </ul>''',
                "Photo_Acquisition_Process": '''<p><b>Photo_Acquisition_Process</b>: Information about how 
                a photograph was acquired by the archive.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Kauf (Purchase)</li>
                <li>Geschenk (Donation)</li>
                <li>Nachlass (Estate)</li>
                </ul>''',
                "Photo_Provenance": '''<p><b>Photo_Provenance</b>: Information about the previous private collection 
                or cultural institution from which a photograph was acquired.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Fabriczy, Cornel von</li>
                <li>Lotz-Bauer, Hilde</li>
                <li>Privatbesitz, Florenz (private possession, Florence)</li>
                <li>Kress Foundation</li>
                </ul>''',
                "Digital_Photo_Storage_Date": '''<p><b>Digital_Photo_Storage_Date</b>: Information about the 
                storage date of a digital image.</p>''',
                "Digital_Photo_File_Format": '''<p><b>Digital_Photo_File_Format</b>: Information about the 
                file format of a digital image (generally "tif").</p>''',
                "Photo_Equipment": '''<p><b>Photo_Equipment</b>: It provides information about the equipment used to 
                create a digital photograph, such details about cameras or scanners.</p>''',
                "Photo_Dimensions": '''<p><b>Photo_Dimensions</b>:  Provides 
                details about the format of historical photographs, expressed as "height x width" in cm. If relevant, it also
                includes the dimensions of the carrier board.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>28,1 x 21,6 cm (Foto)</li>
                <li>34,5 x 24 cm (Karton)</li>
                </ul>''',
                "Photo_Subject": '''<p><b>Photo_Subject</b>: Includes brief, descriptive details about the 
                subject of a photograph. It generally specifies if the photograph represents any details of 
                the artwork or the perspective from which the photograph was taken.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Gesamtansicht (General view)</li>
                <li>Detail des Hauptportals (Detail of the main portal)</li>
                <li>Ausschnitt: Heiliger Bernhard (Section: Saint Bernard)</li>
                <li>Fassadenansicht (View of the facade)</li>
                </ul>''',
                "Photo_Credits": '''<p><b>Photo_Credits</b>: It contains information about photographic credits.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Kunsthistorisches Institut in Florenz – Max-Planck-Institut</li>
                <li>Image provided by Kunsthistorisches Institut in Florenz – Max-Planck-Institut, courtesy of Special Collections, Fine Arts Library, Harvard University</li>
                </ul>''',
                "Photo_Old_Archive_Section": '''<p><b>Photo_Old_Archive_Section</b>: It provides details about the old 
                archival category names used by the KHI, if applicable.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Arch. Renaiss.</li>
                <li>Arch. XIV</li>
                <li>Arch. XIV. u. XVI.</li>
                </ul>''',
                "Photo_Preservation_State": '''<p><b>Photo_Preservation_State</b>: Provides information about the 
                state of preservation of a photograph.</p>
                <p><i>Examples:</i></p>
                <ul>
                <li>Ausbleichen (fading)</li>
                <li>Schimmel (mold)</li>
                <li>Risse (torn paper)</li>
                <li>Knicke (creased paper)</li>
                </ul>'''
}